### PR TITLE
Refactor packages

### PR DESCRIPTION
**Pull request by andrew-d**
See the first commit for more details.  I'm not super-happy with creating *another* package, but I didn't want to duplicate code.

cc #208 and @kortschak

### CODE REVIEW

**Comment by andrew-d** [comment]
Note: TravisCI failures are unrelated - see #246 for a fix.

**Comment by kortschak** [comment]
Please put Load etc in cayley/internal rather than creating util.

Otherwise LGTM

**Comment by andrew-d** [comment]
@kortschak Done :smile:

**Comment by barakmich** [comment]
Merging. Now it's on me to close #208

**Pull request merged**
