### PR TITLE
Add SaveOptional() to save predicates if they exist, and add the

### PR DESCRIPTION
**Pull request by barakmich**
appropriate test.

### CODE REVIEW

**Comment by dennwc** [comment]
Same as https://github.com/google/cayley/pull/365 :)

**Comment by bobbyrullo** [comment]
LGTM, except for that test not passing

**Comment by barakmich** [comment]
The test isn't passing because something is up on tip.

This is the same as #365. So I'm going to merge #365, and change this to incorporate the additional test.

**Comment by bobbyrullo** [comment]
:+1:

**Comment by bobbyrullo** [comment]
and thanks!

**Pull request merged**
