### PR TITLE
bench: Add some grunty Not queries to the integration test (derived from...

### PR DESCRIPTION
**Pull request by barakmich**
... existing queries)

### CODE REVIEW

**Comment by barakmich** [comment]
Merging on my own motion (docs and tests for a recent merge, based on previous tests).

**Comment by kortschak** [comment]
I was trying to understand "the helpless checker, negated (films without Ingrid Bergman)", Can you explain that?

**Comment by barakmich** [comment]
Sure. It's a hard query that produces nothing. The usual query is "people who starred in films, where film name is Casablanca"

The updated query is "people who starred in films, which do not star Ingrid Bergman, named Casablanca" -- which is the null set.

Compare to "people, not named Ingrid Bergman, who starred in a film, named Casablanca"

**Comment by barakmich** [comment]
The "helpless checker" part is that we provide, at the very end, some context ("named Casablanca") -- without that clause, it's a very very broad query. This means the optimizer is going by Check() and not Next()

**Comment by kortschak** [comment]
Ahh, github presents the line in my browser exacly so I expect no further text on the query - I missed the `.Is("Casablanca").All()`, which makes all the difference.

**Pull request merged**
