### PR TITLE
Allow opening a database (bolt, leveldb, mongo) through Go API

### PR DESCRIPTION
**Pull request by Quentin-M**
This small PR allows opening a database through Go code (#208)

**Usage Example**
```
package main

import "github.com/google/cayley"

store, err := cayley.NewGraph("bolt", "/home/mentalow/mexican_coke_db", nil)
if err != nil {
	log.Fatalln(err)
}
```

(CLA Accepted)

### CODE REVIEW

**Comment by barakmich** [comment]
LGTM

**Comment by kortschak** [comment]
I don't like that this is stringly-typed. It made sense when we were do things for a stringly-typed front end but here we have a properly typed™ language as the front end. I think we can improve this by defining and exposing a pair of types that do the work of registration:

```
type Registerer interface {
        NewQuadStore() (graph.QuadStore, error)
}

type DBCreator interface {
        CreateDB(path string, options graph.Options) (graph.QuadStore, error)
}
```

All quadstore packages must provide a Registerer which may also implement DBCreator. The implementation need only be a struct{} with the current function pinned on as methods.

With this we can then say:

```
package main

import "github.com/google/cayley"

store, err := cayley.NewGraph(bolt.Store{}, "/home/mentalow/mexican_coke_db", nil)
if err != nil {
        log.Fatalln(err)
}
```

**Comment by barakmich** [comment]
To be fair to the PR, there's certainly precedent for this style in database/sql.

Whether there's a better way is a perfectly cromulent issue :)

**Comment by kortschak** [comment]
I'm happy to propose this, it's a trivial change.

**Comment by barakmich** [comment]
The registration interface might also wrap the type -- `QuadStoreName() string` or equivalent, as a superset of what exists today.

**Comment by kortschak** [comment]
That seems fair.

**Pull request merged**
